services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password1234
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secure_password
  garage:
    image: dxflrs/garage:v2.3.0
    ports:
      - 3900:3900 # S3 API
      - 3903:3903 # Admin API
    volumes:
      - ./garage.toml:/etc/garage.toml:ro # where the garage.toml is located
    environment:
      GARAGE_DEFAULT_ACCESS_KEY: "68dd215dbffe2a5fbc677e90f502e561"
      GARAGE_DEFAULT_SECRET_KEY: "2586e10351fa5fd0ebbb183c47024628cec9674f862afbe86551a6d819dd2121"
      GARAGE_DEFAULT_BUCKET: "receipts"
    command: ["/garage", "server", "--single-node", "--default-bucket"]


